apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name | default "ha-config" }}
  namespace: {{ .Release.Namespace }}
data:
  hazelcast.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.10.xsd"
                   xmlns="http://www.hazelcast.com/schema/config"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <properties>
        <property name="hazelcast.discovery.enabled">true</property>
      </properties>
      <network>
        <rest-api enabled="true">
          <endpoint-group name="HEALTH_CHECK" enabled="true"/>
        </rest-api>
        <join>
          <multicast enabled="false"/>
          <kubernetes enabled="true">
            <service-name>{{ .Values.service.name | default "hazelcast" }}</service-name>
            <namespace>{{ .Release.Namespace }}</namespace>
            <resolve-not-ready-addresses>true</resolve-not-ready-addresses>
          </kubernetes>
        </join>
      </network>
    </hazelcast>
