apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name | default "ha-config" }}
  namespace: {{ .Release.Namespace }}
data:
  HAZELCAST_KUBERNETES_NAMESPACE: {{ .Release.Namespace }}
  HAZELCAST_KUBERNETES_SERVICE_NAME: {{ .Values.service.name | default "default" }}
