apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name | default "hazelcast" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.metadata.label | default "hazelcast" }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.metadata.label | default "hazelcast" }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port | default "5701" }}
    name: {{ .Values.service.port_name | default "hzport" }}
    nodePort: {{ .Values.service.node_port | default "30571" }}

