apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ .Values.metadata.name | default "hazelcast" }}
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: {{ .Values.metadata.label | default "hazelcast" }}
spec:
  replicas: {{ .Values.ReplicationController.replicas | default "3" }}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.label | default "hazelcast" }}
    spec:
      terminationGracePeriodSeconds: 600
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Values.metadata.label | default "hazelcast" }}
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: hazelcast-node
        image: hazelcast/hazelcast:3.11.2
        ports:
        - containerPort: {{ .Values.service.port | default "5701" }}
        env:
          - name: JAVA_OPTS
            value: "-Dhazelcast.rest.enabled=true -Dhazelcast.config=/data/hazelcast/hazelcast.xml"
        livenessProbe:
          httpGet:
            path: /hazelcast/health/node-state
            port: 5701
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /hazelcast/health/node-state
            port: 5701
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: hazelcast-storage
          mountPath: /data/hazelcast
      volumes:
      - name: hazelcast-storage
        configMap:
          name: {{ .Values.configmap.name }}
