apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ .Values.metadata.name | default "hazelcast" }}
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: {{ .Values.metadata.label | default "hazelcast" }}
spec:
  replicas: {{ .Values.ReplicationController.replicas | default "3" }}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.label | default "hazelcast" }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Values.metadata.label | default "hazelcast" }}
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: hazelcast-node
        image: hazelcast/hazelcast-kubernetes:3.9.3
        ports:
        - containerPort: {{ .Values.service.port | default "5701" }}
        livenessProbe:
          exec:
            command:
            - "./liveness.sh"
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name | default "hz-config" }}
