kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ldapdataclaim
spec:
  storageClassName: yona-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sldapdataclaim
spec:
  storageClassName: yona-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

